export default [
  {
    title: 'Hades',
    genre: ['Roguelite', 'All'],
    dev: 'Supergiant Games',
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard1.html',
  },
  {
    title: 'Risk Of Rain 2',
    genre: ['Roguelite', 'All'],
    dev: ['Hopoo Games', 'PlayEveryWare'],
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard2.html',
  },
  {
    title: '<Realpolitiks 2',
    genre: ['Grand-Strategy', 'All'],
    dev: 'Jujubee',
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard3.html',
  },
  {
    title: '<Hero Siege',
    genre: ['RPG', 'All'],
    dev: ['Panic Art Studios', 'Elias Viglione', 'Jussi Kukkonen'],
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard4.html',
  },
  {
    title: '<Stardew Valley',
    genre: ['Simulation', 'All'],
    dev: ['Eric Barone', 'Sickhead Games', 'ConcernedApe'],
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard5.html',
  },
  {
    title: 'Paralives',
    genre: ['Simulation', 'All'],
    dev: 'Alex Massé',
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard6.html',
  },
  {
    title: 'TaleSpire',
    genre: ['Tabletop', 'All'],
    dev: 'Bouncyrock Entertainment',
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard7.html',
  },
  {
    title: 'SUPERHOT',
    genre: ['Action', 'All'],
    dev: 'SUPERHOT Team',
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard8.html',
  },
  {
    title: 'Shadowrun Returns',
    genre: ['CRPG', 'All'],
    dev: 'Harebrained Schemes',
    image: 'https://placehold.jp/264x352.png',
    location: './pages/gamecard9.html',
  },
];
