export default [
  {
    title: 'Hades',
    tags: ['Roguelite', 'Action'],
    dev: 'Supergiant Games',
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard1.html',
  },
  {
    title: 'Risk Of Rain 2',
    tags: ['Roguelite'],
    dev: ['Hopoo Games', 'PlayEveryWare'],
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard2.html',
  },
  {
    title: 'Realpolitiks 2',
    tags: ['Strategy'],
    dev: 'Jujubee',
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard3.html',
  },
  {
    title: 'Hero Siege',
    tags: ['RPG'],
    dev: ['Panic Art Studios', 'Elias Viglione', 'Jussi Kukkonen'],
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard4.html',
  },
  {
    title: 'Stardew Valley',
    tags: ['Simulation', 'RPG'],
    dev: ['Eric Barone', 'Sickhead Games', 'ConcernedApe'],
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard5.html',
  },
  {
    title: 'Paralives',
    tags: ['Simulation', 'RPG'],
    dev: 'Alex Massé',
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard6.html',
  },
  {
    title: 'TaleSpire',
    tags: ['Tabletop'],
    dev: 'Bouncyrock Entertainment',
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard7.html',
  },
  {
    title: 'SUPERHOT',
    tags: ['Action'],
    dev: 'SUPERHOT Team',
    image: 'https://placehold.jp/264x352.png',
    location: './gamecard8.html',
  },
];
